In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [4]:
file_path = 'C:/AI/iris.data'

#class = Iris Setosa, Iris Versicolour, Iris Virginica
column_names = ["sepal length ", "sepal width ", "petal length ", "petal width ", "class"]          

df = pd.read_csv(file_path, header=None, names=column_names)

df.head(10)

   sepal length   sepal width   petal length   petal width         class
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           3.4            1.5           0.2  Iris-setosa
8            4.4           2.9            1.4           0.2  Iris-setosa
9            4.9           3.1            1.5           0.1  Iris-setosa

In [5]:
X=df.drop('class',axis=1)
X.head()

   sepal length   sepal width   petal length   petal width
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [6]:
y=df['class']
y.head(10)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
5    Iris-setosa
6    Iris-setosa
7    Iris-setosa
8    Iris-setosa
9    Iris-setosa
Name: class, dtype: object

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [8]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [9]:
iris_ML = LogisticRegression(random_state=0)
iris_ML.fit(X_train, y_train)

pred_iris_ML = iris_ML.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_iris_ML))
print (confusion_matrix(y_test, pred_iris_ML))

--- Logistic Regression Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]

In [10]:
iris_ML = LogisticRegression(random_state=0, max_iter=1000)
iris_ML.fit(X_train, y_train)

pred_iris_ML = iris_ML.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_iris_ML))
print (confusion_matrix(y_test, pred_iris_ML))

--- Logistic Regression Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]

In [11]:

X_train

     sepal length   sepal width   petal length   petal width
61             5.9           3.0            4.2           1.5
92             5.8           2.6            4.0           1.2
112            6.8           3.0            5.5           2.1
2              4.7           3.2            1.3           0.2
141            6.9           3.1            5.1           2.3
..             ...           ...            ...           ...
9              4.9           3.1            1.5           0.1
103            6.3           2.9            5.6           1.8
67             5.8           2.7            4.1           1.0
117            7.7           3.8            6.7           2.2
47             4.6           3.2            1.4           0.2

[112 rows x 4 columns]

In [12]:

y_train

61     Iris-versicolor
92     Iris-versicolor
112     Iris-virginica
2          Iris-setosa
141     Iris-virginica
            ...
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: class, Length: 112, dtype: object

In [13]:
X_test

     sepal length   sepal width   petal length   petal width
114            5.8           2.8            5.1           2.4
62             6.0           2.2            4.0           1.0
33             5.5           4.2            1.4           0.2
107            7.3           2.9            6.3           1.8
7              5.0           3.4            1.5           0.2
100            6.3           3.3            6.0           2.5
40             5.0           3.5            1.3           0.3
86             6.7           3.1            4.7           1.5
76             6.8           2.8            4.8           1.4
71             6.1           2.8            4.0           1.3
134            6.1           2.6            5.6           1.4
51             6.4           3.2            4.5           1.5
73             6.1           2.8            4.7           1.2
54             6.5           2.8            4.6           1.5
63             6.1           2.9            4.7           1.4
37             4.9           3.1            1.5           0.1
78             6.0           2.9            4.5           1.5
90             5.5           2.6            4.4           1.2
45             4.8           3.0            1.4           0.3
16             5.4           3.9            1.3           0.4
121            5.6           2.8            4.9           2.0
66             5.6           3.0            4.5           1.5
24             4.8           3.4            1.9           0.2
8              4.4           2.9            1.4           0.2
126            6.2           2.8            4.8           1.8
22             4.6           3.6            1.0           0.2
44             5.1           3.8            1.9           0.4
97             6.2           2.9            4.3           1.3
93             5.0           2.3            3.3           1.0
26             5.0           3.4            1.6           0.4
137            6.4           3.1            5.5           1.8
84             5.4           3.0            4.5           1.5
27             5.2           3.5            1.5           0.2
127            6.1           3.0            4.9           1.8
132            6.4           2.8            5.6           2.2
59             5.2           2.7            3.9           1.4
18             5.7           3.8            1.7           0.3
83             6.0           2.7            5.1           1.6

In [14]:
y_test

114     Iris-virginica
62     Iris-versicolor
33         Iris-setosa
107     Iris-virginica
7          Iris-setosa
100     Iris-virginica
40         Iris-setosa
86     Iris-versicolor
76     Iris-versicolor
71     Iris-versicolor
134     Iris-virginica
51     Iris-versicolor
73     Iris-versicolor
54     Iris-versicolor
63     Iris-versicolor
37         Iris-setosa
78     Iris-versicolor
90     Iris-versicolor
45         Iris-setosa
16         Iris-setosa
121     Iris-virginica
66     Iris-versicolor
24         Iris-setosa
8          Iris-setosa
126     Iris-virginica
22         Iris-setosa
44         Iris-setosa
97     Iris-versicolor
93     Iris-versicolor
26         Iris-setosa
137     Iris-virginica
84     Iris-versicolor
27         Iris-setosa
127     Iris-virginica
132     Iris-virginica
59     Iris-versicolor
18         Iris-setosa
83     Iris-versicolor
Name: class, dtype: object